version: '3'
services:
  frontend:
    build:
      context: /src/frontend # Path to the frontend app (where the Vue.js Dockerfile is)
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: / # Path to the backend app (where the Spring Boot Dockerfile is)
    ports:
      - "8080:8080"
